### ISSUE TITLE
media-gfx/loupe has an undeclared runtime dependency on sys-apps/bubblewrap

### ISSUE THREAD

**Issue by anhollander516** [Loatchi/gentoo-overlay#3]
![Screenshot from 2024-02-23 09-02-06](https://github.com/Loatchi/loatchi-overlay/assets/82128012/4e9610c7-a70d-47f0-8972-31a9019f2383)
Loupe requires bubblewrap in order to actually display images, but it isn't declared in RDEPEND, resulting in this happening unless bubblewrap is manually installed.

**Comment by Loatchi** [comment]
You are indeed right ! Thanks for pointing it out !

I've added `sys-apps/bubblewrap` as a dependency to `media-libs/glycin`, it should fix the issue.
