### ISSUE TITLE
games-util/ferium: BDEPEND would be better as >=virtual/rust-1.75.0

### ISSUE THREAD

**Issue by joaompssantos** [Loatchi/gentoo-overlay#4]
A better BDEPEND for ferium would probably be >=virtual/rust-1.75.0, which would allow to account for both dev-lang/rust and dev-lang/rust-bin (which I use in my system).

I have tested manually changing this in the ebuild locally with no issues.

**Comment by Loatchi** [comment]
You are absolutely right, thanks for pointing it out !
