### ISSUE TITLE
gnome-extra/gdm-settings needs version bump

### ISSUE THREAD

**Issue by ppw0** [Loatchi/gentoo-overlay#5]
After the recent switch to Python 3.12 as the default Python target, gnome-extra/gdm-settings-4.3 will prevent any further action by emerge with the following message:
```
~% sudo emerge -avDNu @world                           

Local copy of remote index is up-to-date and will be used.

These are the packages that would be merged, in order:

Calculating dependencies -

!!! Problem resolving dependencies for gnome-extra/gdm-settings from @selected
... done!
Dependency resolution took 2.63 s (backtrack: 0/20).


!!! The ebuild selected to satisfy "gnome-extra/gdm-settings" has unmet requirements.
- gnome-extra/gdm-settings-4.3::loatchi USE="" ABI_X86="(64)" L10N="-ar -bn -ca -cs -de -es -eu -fa -fi -fr -he -hi -id -it -ja -ka -ko -nb -nl -oc -pl -pt -pt_BR -ru -sv -tr -uk -ur -vi -zh" PYTHON_SINGLE_TARGET="-python3_10 -python3_11"

  The following REQUIRED_USE flag constraints are unsatisfied:
    exactly-one-of ( python_single_target_python3_10 python_single_target_python3_11 )

(dependency required by "@selected" [set])
(dependency required by "@world" [argument])
```
Maybe it would be a good idea to bump gdm-settings to version 4.4 to allieviate this?

**Comment by Loatchi** [comment]
I did a month ago a commit that should have addressed the PYTHON_COMPAT problem, I forgot gdm-settings in the process, which is my bad.

I've added gdm-settings-4.4, I've tested it with python3.11, it works. I am on the rush about my exams, and I haven't tested it with 3.12, although I don't see why it wouldn't work.

If any problem occurs, feel free to reopen this thread.
